name: Jupyter

on:
  workflow_dispatch:
  schedule:
    # 8h30 heure d'hiver (CET, UTC+1) => 7h30 UTC
    - cron: '30 7 * * *'
    # 8h30 heure d'été (CEST, UTC+2) => 6h30 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade jupyter
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute Notebook
        run: |
          jupyter nbconvert --to notebook --execute --inplace linkedinCoding.ipynb

      - name: Upload Executed Notebook
        uses: actions/upload-artifact@v3.2.1-node20
        with:
          name: executed-notebook
          path: linkedinCoding.ipynb  # Adjust if your notebook has a different name or location
          if-no-files-found: warn
          retention-days: 30
          include-hidden-files: false
