name: Jupyter

on:
  workflow_dispatch:
  schedule:
    - cron: '02 10 * * *'  # Exécuter tous les jours à 10h02 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter
          pip install -r requirements.txt  # Si vous avez des dépendances Python à installer

      - name: Execute Notebook
        run: jupyter nbconvert --to notebook --execute --inplace linkedinCoding.ipynb

      - name: Commit and Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --local user.name "Schmied07"
          git config --local user.email "talomthibaut@gmail.com"
          git add linkedinCoding.ipynb
          git commit -m "Executed notebook"
          git push https://Schmied07:${{ secrets.PAT_TOKEN }}@github.com/Schmied07/Tetrisnews-Linkedin.git
